name: Node.js CI

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  test:
    runs-on: ubuntu-latest
  
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 16.x 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install environment
      run: |
        sudo apt update
        sudo apt install git chromium-browser
        yarn global add @angular/cli

    - name: Install dependencies
      run: yarn install && ng update
    
    - name: Build stage version
      run: ng build --configuration=production
    
    - name: Store build artifact
      uses: actions/upload-artifact@v3
      with: 
        name: stage
        path: dist/shitcoin-factory-frontend
        retention-days: 3

    - name: Deploy to S3
      uses: reggionick/s3-deploy@v3
      with:
        folder: dist/shitcoin-factory-frontend
        bucket: ${{ secrets.S3_BUCKET_PROD }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
